name: fadeu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- FIX: Ensuring all necessary packages are here ---
  flutter_local_notifications: ^18.0.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # Other dependencies
  animated_text_kit: ^4.2.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.0
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  timezone: ^0.9.4
  workmanager: ^0.7.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/database/dictionary.db

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
