# Generated by Django 4.2.7 on 2025-07-08 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwordprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='word_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userwordprogress',
            unique_together={('user', 'word_id')},
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='word',
        ),
    ]
